server:
  port: 9990

spring:
  datasource:
    url: jdbc:h2:./db/java_19_Edu_Food;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  mvc:
    static-path-pattern: /static/**
  #  h2:
  #    console:
  #      enabled: true
  freemarker:
    expose-session-attributes: true
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
    org.springframework.security: debug

  file:
    name: logs/java_19_Edu_Food.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 5